### ISSUE TITLE
Wrong bp grammar

### ISSUE THREAD

**Issue by Vlad8161** [pvoid/AndroidBlueprintPlugin#25]
Hello, I'm trying to open android12L-gsi branch with this plugin, but it seems that Blueprint syntax in Android.bp differs the one described in plugin. For example:

![image](https://user-images.githubusercontent.com/11634441/176954620-c1fe57f4-a4fc-431d-96e8-7ac42cdb70d8.png)

Parser expects = or += but gets value instead. So maybe actual .bp syntax was changed.

**Comment by pvoid** [comment]
By now I work on Android 10 fork so not following the BP syntax updates.  I've added the syntax support but there is no autocompletion still. To add it I need your help. Can you, please, check our out folder for `out/soong/docs`. There are HTML files there, can you please zip them and attach them to the issue. Thanks.

**Comment by Vlad8161** [comment]
Of course, here it is:
[android12L-gsi-soongdocs.zip](https://github.com/pvoid/AndroidBlueprintPlugin/files/9033256/android12L-gsi-soongdocs.zip)

**Comment by Vlad8161** [comment]
By the way I think I solve this. The problem is that lexer interprets words 'package' and 'license' as a variable instead a blueprint, so i've added 'package' and 'license' to BLUEPRINT_NAME macro and highlighting now works correct, but project structure does not seems to be built. Now trying to fix this.

**Comment by pvoid** [comment]
So the same as here then. But it's not enough to fix autocompletion and I am not sure that BP parsing will work correctly anyway. Looks like the visibility model was introduced and the plugin doesn't take it into the account as for now. 

https://github.com/pvoid/AndroidBlueprintPlugin/commit/6e45ec36bedfa4bb214aebe76f718f8204561452

**Comment by pvoid** [comment]
Should be fixed now. You can build the plugin manually if you want the change asap.
